---
- name: create and control a VM on proxmox using Ascender
  hosts: localhost
  gather_facts: false
  vars:
    # Configure the api connection info for proxmox host
    proxmox_auth: &proxmox_auth
      api_host: proxmox.gregsowell.com
      api_user: "{{ gen1_user }}"
      # api_user: root@pam # username format example
      # Use standard password
      api_password: "{{ gen1_pword }}"
      # Use api token and secret - example format
      # api_token_id: gregisa5.0
      # api_token_secret: 72a72987-ff68-44f1-9fee-c09adaaecf4d

    # Configure template to clone for new vm
    clone_template: rocky9-template

    # Configure location on Host to store new vm
    storage_location: local-lvm

    # Linked Clone needs format=unspecified and full=false
    # Format of new VM
    vm_format: qcow2

    # Default name to use for the VM
    vm_name: test-rocky9

    # Switches for playbook control
#    vm_action: provision
    # vm_action: start
    # vm_action: stop

# https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html#examples
# https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_vm_info_module.html#examples
# https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html#examples

  tasks:
  - name: Block for creating a vm
    when: vm_action == "provision"
    block:
    - name: Create a VM based on a template
      community.general.proxmox_kvm:
        # api_user: root@pam
        # api_password: secret
        # api_host: helldorado
        <<: *proxmox_auth
        clone: "{{ clone_template }}"
        name: "{{ vm_name }}"
        node: proxmox
        storage: "{{ storage_location }}"
        format: "{{ vm_format }}"
        timeout: 500

    - name: Pause after provision to give the API a chance to catch up
      ansible.builtin.pause:
        seconds: 10

  - name: Start VM
    when: vm_action == "provision" or vm_action == "start"
    community.general.proxmox_kvm:
      <<: *proxmox_auth
      name: "{{ vm_name }}"
      node: proxmox
      state: started

  - name: Stop VM
    when: vm_action == "stop"
    community.general.proxmox_kvm:
      <<: *proxmox_auth
      name: "{{ vm_name }}"
      node: proxmox
      state: stopped
